#!/bin/sh
set -eu

cat > GameServer.properties <<EOF
# Generated by the local Docker entrypoint.
database.host       = ${DB_HOST:-db}
database.port       = ${DB_PORT:-3306}
database.database   = ${DB_DATABASE:-openpanfu}
database.user       = ${DB_USERNAME:-openPanfu}
database.pass       = ${DB_PASSWORD:-password}
database.allowPublicKeyRetrieval = ${DB_ALLOW_PUBLIC_KEY_RETRIEVAL:-false}

gameserver.ansilogging = 1

treehouses.showSheriffAsGold = 0

chat.commands.prefix = !
chat.sheriff.prefix = FF0000
chat.forcesafechat = 0

chat.antispam.enabled = 1
chat.antispam.secondsbetweenmessages = 1
chat.antispam.warnings = 3
chat.antispam.message = You're sending too many messages! Warning &&warns&&/&&maxwarns&&

actions.antispam.enabled = 1
actions.antispam.secondsbetweenactions = 1
actions.antispam.message = You're performing too many actions! Warning &&warns&&/&&maxwarns&&

rooms.pool.jumpintotheshowers = 0
EOF

exec java -jar gameserver.jar
